syntax = "proto3";

package C4;

enum MessageType {
  Command = 0;
  Event   = 1;
}

message EventServerConnected {
  uint32 client_id = 1;
}

message EventUsernameCheckFailed {}

enum GameState {
  GAME_STATE_WAITING = 0;
  GAME_STATE_IN_GAME = 1;
  GAME_STATE_VERDICT = 2;
}

message GameInfo {
  uint32    id         = 1;
  uint32    player1_id = 2;
  uint32    player2_id = 3;
  GameState state      = 4;
}

enum ClientState {
  CLIENT_STATE_USERNAME = 0;
  CLIENT_STATE_LOBBY    = 1;
  CLIENT_STATE_IN_GAME  = 2;
}

message ClientInfo {
  uint32      id       = 1;
  string      username = 2;
  ClientState state    = 3;
}

message EventLobbyUpdated {
  uint32              total_clients = 1;
  repeated ClientInfo clients       = 2;
  uint32              total_games   = 3;
  repeated GameInfo   games         = 4;
}

message EventLobbyEntered {}

message EventNewGameInviteReceived {
  uint32 inviter_client_id = 1;
  string inviter_username  = 2;
}

message EventNewGameJoined {
  uint32 game_id            = 1;
  uint32 opponent_client_id = 2;
  string opponent_username  = 3;
}

message EventGameCreated {
  uint32 game_id    = 1;
  uint32 player1_id = 2;
}

message EventPlayerJoined {
  uint32 game_id    = 1;
  uint32 player2_id = 2;
}

message EventGameStarted { uint32 game_id = 1; }

message EventPlayerMadeMove {
  uint32 game_id       = 1;
  uint32 player_id     = 2;
  uint32 played_column = 3;
}

message EventGameVerdicted {
  uint32 game_id      = 1;
  uint32 game_verdict = 2;
}

message EventPlayerLeft {
  uint32 game_id   = 1;
  uint32 player_id = 2;
}

message EventPayload {
  oneof payload {
    EventServerConnected       event_server_connected         = 1;
    EventUsernameCheckFailed   event_username_check_failed    = 2;
    EventLobbyUpdated          event_lobby_updated            = 3;
    EventLobbyEntered          event_lobby_entered            = 4;
    EventNewGameInviteReceived event_new_game_invite_received = 5;
    EventNewGameJoined         event_new_game_joined          = 6;
    EventGameCreated           event_game_created             = 7;
    EventPlayerJoined          event_player_joined            = 8;
    EventGameStarted           event_game_started             = 9;
    EventPlayerMadeMove        event_player_made_move         = 10;
    EventGameVerdicted         event_game_verdicted           = 11;
    EventPlayerLeft            event_player_left              = 12;
  }
}

message CommandEnterLobby {
  string username = 1;
}

message CommandNewGameInvite {
  uint32 client_id = 1;
}

message CommandInviteAccept {
  uint32 inviter_client_id = 1;
}

message CommandJoinGame {
  uint32 game_id = 1;
}

message CommandStartGame {
  uint32 game_id = 1;
}

message CommandPlayerMakeMove {
  uint32 game_id       = 1;
  uint32 player_id     = 2;
  uint32 played_column = 3;
}

message CommandPlayerLeave {
  uint32 game_id   = 1;
  uint32 player_id = 2;
}

message CommandPayload {
  oneof payload {
    CommandEnterLobby     command_enter_lobby     = 1;
    CommandNewGameInvite  command_new_game_invite = 2;
    CommandInviteAccept   command_invite_accept   = 3;
    CommandJoinGame       command_join_game       = 4;
    CommandStartGame      command_start_game      = 5;
    CommandPlayerMakeMove command_make_move       = 6;
    CommandPlayerLeave    command_player_leave    = 7;
  }
}

message Message {
  uint32 id = 1;
  oneof payload_type {
    EventPayload   event_payload   = 2;
    CommandPayload command_payload = 3;
  }
}